/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_advanced;

import java.io.File;
import java.io.InputStream;
import java.io.PrintStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Scanner;
import java.util.Vector;

public class App {
    public static void main(String[] args) {
        try {
            var stdScanner = new Scanner(System.in);
            var file = new File("/home/dungph/thu_vien.txt");
            if (file.exists()) {
            } else {
                file.createNewFile();
            }
            var callcards = new Vector<TheMuon>();

            int choose;
            do {
                System.out.println("1: Nhap tu ban phim");
                System.out.println("2: In ra man hinh");
                System.out.println("3: Nhap tu file (/home/dungph/thu_vien.txt)");
                System.out.println("4: In ra file (/home/dungph/thu_vien.txt)");
                System.out.println("5: Thoat");
                choose = Integer.parseInt(stdScanner.nextLine());
                if (choose == 1) {
                    callcards = inputCallCards(true, stdScanner);
                } else if (choose == 2) {
                    outputCallCards(callcards, System.out);
                } else if (choose == 3) {

                    var fileScanner = new Scanner(file);

                    callcards = inputCallCards(false, fileScanner);
                } else if (choose == 4) {
                    var filePrint = new PrintStream(file);

                    outputCallCards(callcards, filePrint);
                    filePrint.close();
                }
            } while (choose > 0 && choose < 5);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static Vector<TheMuon> inputCallCards(boolean isStdin, Scanner scann) {

        var ret = new Vector<TheMuon>();
        if (isStdin) {
            System.out.println("Nhap so luong");
        }
        var n = Integer.parseInt(scann.nextLine());
        for (int i = 0; i < n; i++) {
            ret.add(TheMuon.inputCallCard(isStdin, scann));
        }
        return ret;
    }

    public static void outputCallCards(Vector<TheMuon> callcards, PrintStream fileOutput) {
        fileOutput.println(callcards.size());
        for (TheMuon callcard : callcards) {
            callcard.printCallCard(fileOutput);
        }
    }
}

class DateFmt {
    static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/M/y");
}

class TheMuon {
    String id;
    LocalDate from;
    LocalDate to;
    String bookId;
    SinhVien student;

    public static TheMuon inputCallCard(boolean isStdin, Scanner input) {
        var ret = new TheMuon();
        if (isStdin) {
            System.out.println("Nhap so the: ");
        } else {
            input.nextLine();
        }
        ret.id = input.nextLine();
        if (isStdin) {
            System.out.println("Nhap ngay muon (%d/%m/%Y): ");
        } else {
            input.nextLine();
        }
        ret.from = LocalDate.parse(input.nextLine(), DateFmt.formatter);
        if (isStdin) {
            System.out.println("Nhap ngay tra (%d/%m/%Y): ");
        } else {
            input.nextLine();
        }
        ret.to = LocalDate.parse(input.nextLine(), DateFmt.formatter);
        if (isStdin) {
            System.out.println("Nhap ma sach: ");
        } else {
            input.nextLine();
        }
        ret.bookId = input.nextLine();
        ret.student = SinhVien.inputStudent(isStdin, input);
        return ret;
    }

    public void printCallCard(PrintStream out) {
        out.println("[Thong tin the muon]");
        out.println(id);
        out.println("Ngay muon:");
        out.println(from.format(DateFmt.formatter));
        out.println("Ngay tra:");
        out.println(to.format(DateFmt.formatter));
        out.println("Ma sach");
        out.println(bookId);
        student.printStudent(out);
    }
}

class SinhVien {
    String studentName;
    int studentAge;
    String studentClass;

    public static SinhVien inputStudent(boolean isStdin, Scanner input) {
        var ret = new SinhVien();
        if (isStdin) {
            System.out.println("Ten sinh vien: ");
        } else {
            input.nextLine();
        }
        ret.studentName = input.nextLine();

        if (isStdin) {
            System.out.println("Tuoi sinh vien: ");
        } else {
            input.nextLine();
        }
        ret.studentAge = Integer.parseInt(input.nextLine());

        if (isStdin) {
            System.out.println("Lop: ");
        } else {
            input.nextLine();
        }
        ret.studentClass = input.nextLine();
        return ret;
    }

    public void printStudent(PrintStream out) {
        out.println("Sinh vien:");
        out.println(studentName);
        out.println("Tuoi:");
        out.println(studentAge);
        out.println("Lop:");
        out.println(studentClass);
    }
}
